import { 
  AdmissionStep, 
  PricingPlan, 
  ComparisonFeature, 
  Scholarship, 
  AdmissionRequirement, 
  AdmissionFAQ, 
  ConsultationOption 
} from "./admissions.types";

export const ADMISSION_STEPS_DATA: AdmissionStep[] = [
  {
    id: "step-1",
    stepNumber: 1,
    title: "Enroll Online",
    description: "Submit parent contact details and create the student profile in less than 3 minutes.",
    duration: "Est. 3 mins",
    iconName: "UserPlus",
  },
  {
    id: "step-2",
    stepNumber: 2,
    title: "Student Assessment",
    description: "The student undergoes a diagnostic evaluation in STEM & Logic to map pre-requisite levels.",
    duration: "Est. 45 mins",
    iconName: "Binary",
  },
  {
    id: "step-3",
    stepNumber: 3,
    title: "Parent Consultation",
    description: "Our academic advisors schedule a virtual sync to review diagnostic findings and roadmap.",
    duration: "Est. 20 mins",
    iconName: "Video",
  },
  {
    id: "step-4",
    stepNumber: 4,
    title: "Personalized Study Plan",
    description: "We configure the Socratic AI parameters and calendar limits tuned to the child's pacing.",
    duration: "Est. 1 day",
    iconName: "Sliders",
  },
  {
    id: "step-5",
    stepNumber: 5,
    title: "Enrollment",
    description: "Select your preferred billing options, set up billing parameters, and confirm student portal access.",
    duration: "Est. 5 mins",
    iconName: "ShieldCheck",
  },
  {
    id: "step-6",
    stepNumber: 6,
    title: "Learning Begins",
    description: "Immediate access to the Socratic dashboard, standard curriculum modules, and AI co-pilots.",
    duration: "Immediate",
    iconName: "Sparkles",
  },
];

export const PRICING_PLANS_DATA: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter AI Scholar",
    description: "Perfect for independent learners seeking structured AI diagnostic guides and socratic assistance.",
    monthlyPrice: "$29",
    annualPrice: "$19",
    recommended: false,
    popular: false,
    features: [
      "Full Cambridge Syllabus Modules",
      "Socratic AI Equation Decomposer",
      "Structured Video Explanations",
      "Standard Study Mode",
    ],
    aiFeatures: ["100 Socratic sessions/mo", "Basic Diagnostic Engine"],
    supportLevel: "Email Support (24h turnaround)",
    learningResources: "EBM Digital Library (View-only)",
    assessmentAccess: "1 Mock Exam per Semester",
    parentDashboard: false,
    certificateEligible: false,
  },
  {
    id: "student",
    name: "Accelerated Student",
    description: "Highly recommended for students aiming for raw A* grades through full diagnostic tracking.",
    monthlyPrice: "$59",
    annualPrice: "$45",
    recommended: true,
    popular: true,
    badge: "Most Popular",
    features: [
      "Everything in Starter Plan",
      "Unlimited Socratic AI Dialogues",
      "Custom Math & Chemistry Worksheets",
      "Real-time Misconception Spotting",
    ],
    aiFeatures: ["Unlimited Socratic sessions", "Deep Core Diagnostic Engine", "AI Error Log Analysis"],
    supportLevel: "Priority Ticket Support (4h turnaround)",
    learningResources: "Full Library Access + PDF Downloads",
    assessmentAccess: "Weekly Mini-Diagnostic Quizzes",
    parentDashboard: true,
    certificateEligible: true,
  },
  {
    id: "premium",
    name: "Socratic Premium",
    description: "Designed for premium scholars requiring personal mentoring circles and oral presentations.",
    monthlyPrice: "$129",
    annualPrice: "$95",
    recommended: false,
    popular: false,
    features: [
      "Everything in Accelerated Student",
      "Bi-weekly Teacher-Led Circles",
      "Live Academic Debates & Essays",
      "Priority Writing Evaluation Engine",
    ],
    aiFeatures: ["Socratic AI Dialogue Assistant", "Personalized Exam Predictive Analyzer", "Essay Structure Feedback Engine"],
    supportLevel: "Direct Whatsapp Advisor Liaison",
    learningResources: "Complete Archive + Premium Resource Packs",
    assessmentAccess: "Unlimited Diagnostic & Adaptive Quizzes",
    parentDashboard: true,
    certificateEligible: true,
  },
  {
    id: "family",
    name: "EBM Family Suite",
    description: "Ideal for households with up to 3 active scholars. Complete synchronization and multi-profile discounts.",
    monthlyPrice: "$189",
    annualPrice: "$139",
    recommended: false,
    popular: false,
    features: [
      "3 Independent Student Profiles",
      "Shared Diagnostic Overview",
      "Cross-Scholar Study Sprints",
      "Unified Parent Billing Account",
    ],
    aiFeatures: ["Shared AI credits with full limits", "Multi-Student Progress Comparison"],
    supportLevel: "Dedicated Family Success Coordinator",
    learningResources: "Full Library & Collaborative Workspaces",
    assessmentAccess: "Standardized & Custom Drills",
    parentDashboard: true,
    certificateEligible: true,
  },
  {
    id: "institution",
    name: "EBM Institutional Partner",
    description: "Configured for schools, academies, and homeschooling communities needing full administrative analytics.",
    monthlyPrice: "Custom",
    annualPrice: "Custom",
    recommended: false,
    popular: false,
    badge: "For Schools",
    features: [
      "White-labeled School Portal",
      "Teacher Course Creators",
      "Direct Class Activity Monitors",
      "Unified Admin API Database Mappings",
    ],
    aiFeatures: ["Custom School Socratic LLM Tuning", "Bulk Misconception Cohort Heatmaps"],
    supportLevel: "SLA-Backed 24/7 Phone & Email Support",
    learningResources: "Custom Curriculum Upload Capabilities",
    assessmentAccess: "Institutional Standard Exams & Rubrics",
    parentDashboard: true,
    certificateEligible: true,
  },
];

export const FEATURE_COMPARISON_DATA: ComparisonFeature[] = [
  {
    id: "f-1",
    category: "AI & Socratic Engines",
    name: "Socratic AI Equation Decomposer",
    starter: "100 runs / mo",
    student: "Unlimited",
    premium: "Unlimited + Priority Speed",
    family: "Unlimited (up to 3 users)",
    institution: "Custom Enterprise Tuning",
  },
  {
    id: "f-2",
    category: "AI & Socratic Engines",
    name: "AI Core Misconception Pinpoint",
    starter: false,
    student: true,
    premium: true,
    family: true,
    institution: "Cohort Aggregated Metrics",
  },
  {
    id: "f-3",
    category: "Academics",
    name: "Cambridge Syllabus Curriculum",
    starter: true,
    student: true,
    premium: true,
    family: true,
    institution: "True + Custom Syllabi",
  },
  {
    id: "f-4",
    category: "Academics",
    name: "Teacher-Led Discussion Circles",
    starter: false,
    student: false,
    premium: "Bi-weekly Circles",
    family: "Bi-weekly Circles",
    institution: "Dedicated Live Lecturers",
  },
  {
    id: "f-5",
    category: "Assessment",
    name: "Adaptive Micro-Drills",
    starter: "Limited",
    student: "Weekly Tests",
    premium: "Unlimited Adaptive",
    family: "Unlimited Adaptive",
    institution: "Unified Standard Rubrics",
  },
  {
    id: "f-6",
    category: "Parent Visibility",
    name: "Real-time Parent Monitoring",
    starter: false,
    student: true,
    premium: true,
    family: "Unified Household Portal",
    institution: "School Counselor View",
  },
  {
    id: "f-7",
    category: "Portfolios",
    name: "EBM Scholar Certificate & Portfolio",
    starter: false,
    student: true,
    premium: true,
    family: true,
    institution: "Verifiable Block Credentials",
  },
  {
    id: "f-8",
    category: "Support",
    name: "Advisor Support SLA",
    starter: "24h Email",
    student: "4h Priority Ticket",
    premium: "Direct WhatsApp",
    family: "Family Coordinator",
    institution: "Dedicated Account Manager",
  },
];

export const SCHOLARSHIPS_DATA: Scholarship[] = [
  {
    id: "sch-1",
    title: "Need-Based Financial Aid",
    eligibility: "Households with demonstrated income thresholds under global median criteria.",
    description: "EBM provides subsidized scholarships ensuring digital tools remain inclusive for scholars worldwide.",
    discountPercentage: "Up to 80%",
    iconName: "HeartHandshake",
  },
  {
    id: "sch-2",
    title: "Socratic Merit Excellence",
    eligibility: "Students scoring top 2% in the EBM Diagnostic & STEM Aptitude Evaluation.",
    description: "Rewarded to applicants displaying high critical reasoning and dedicated study habits during initial trials.",
    discountPercentage: "50% Discount",
    iconName: "Award",
  },
  {
    id: "sch-3",
    title: "Sibling Co-Cohort Discount",
    eligibility: "Active households enrolling more than one sibling concurrently.",
    description: "We ease the path for multi-scholar families to maintain unified active diagnostic monitoring.",
    discountPercentage: "15% Sibling Credit",
    iconName: "Users",
  },
  {
    id: "sch-4",
    title: "Institutional Partnerships",
    eligibility: "Homeschooling associations or partner charter schools under active collaboration models.",
    description: "Providing unified rates and administration parameters to support integrated digital education ecosystems.",
    discountPercentage: "Custom Partner Rates",
    iconName: "GraduationCap",
  },
];

export const ADMISSION_REQUIREMENTS_DATA: AdmissionRequirement[] = [
  {
    id: "req-1",
    category: "Academic Requirements",
    title: "Prerequisite Placement Assessment",
    status: "required",
    description: "Every student must complete a diagnostic placement module to adjust the Socratic AI parameters.",
  },
  {
    id: "req-2",
    category: "Academic Requirements",
    title: "Previous Transcript Submission",
    status: "optional",
    description: "Upload prior school report cards to help advisor consultants cross-reference mastery records.",
  },
  {
    id: "req-3",
    category: "Hardware & Tech",
    title: "Stable Internet & Web Browsing Terminal",
    status: "required",
    description: "Minimum speed of 5Mbps. Required to load the interactive canvas visualizers and stream explanatory drills.",
  },
  {
    id: "req-4",
    category: "Hardware & Tech",
    title: "Standard Modern Web Browser",
    status: "required",
    description: "Chrome, Safari, or Edge browser. Recommended on tablets, Chromebooks, or standard laptops/desktops.",
    devices: ["Laptop", "Desktop", "Tablet", "Chromebook"],
  },
  {
    id: "req-5",
    category: "Student Commitment",
    title: "Daily Focus Practice Commitment",
    status: "recommended",
    description: "Minimum of 15 minutes of uninterrupted, deliberate study every day to maintain learning streak integrity.",
  },
];

export const ADMISSION_FAQS_DATA: AdmissionFAQ[] = [
  {
    id: "faq-1",
    category: "Enrollment & Age Groups",
    question: "Who can join the EBM Learning Ecosystem?",
    answer: "EBM is designed for secondary scholars preparing for Cambridge IGCSE, O Level, and foundation STEM pathways (typically ages 12 to 18). However, self-directed accelerated learners of other age cohorts are welcome to complete diagnostic trials.",
  },
  {
    id: "faq-2",
    category: "Instruction Methodology",
    question: "How does EBM's Socratic learning model work?",
    answer: "Unlike traditional platforms that immediately supply complete equations or direct copy-paste answers, our Socratic AI breaks down problems. It asks questions that lead students to discover foundational concepts themselves, building robust long-term retention.",
  },
  {
    id: "faq-3",
    category: "Assessments & Diagnostics",
    question: "How are student assessments and analytics handled?",
    answer: "Assessments are adaptive. They analyze time-to-respond, conceptual accuracy, and keystroke confidence. If a student makes an error, the engine updates their personal mastery map, which parents can review live in their portal.",
  },
  {
    id: "faq-4",
    category: "Transfers & Alignment",
    question: "Can my child transition from a standard school mid-semester?",
    answer: "Yes. EBM's micro-modular syllabus is fully self-paced. During enrollment, our diagnostic test isolates what modules they have already mastered elsewhere, allowing them to start exactly where they need to without wasting time.",
  },
  {
    id: "faq-5",
    category: "Admissions & Advising",
    question: "Is there a physical school requirement or is it entirely digital?",
    answer: "EBM is fully digital and functions perfectly as a complete learning ecosystem, a structured homeschooling curriculum, or an after-school booster. You do not need physical classrooms.",
  },
  {
    id: "faq-6",
    category: "Hardware & Subscriptions",
    question: "What devices do students require to engage with EBM?",
    answer: "Any standard tablet, laptop, desktop, or Chromebook with internet access is supported. The platform is highly responsive and designed to optimize low-bandwidth setups dynamically.",
  },
];

export const CONSULTATION_OPTIONS_DATA: ConsultationOption[] = [
  {
    id: "consult-1",
    title: "Virtual Advisor Meeting",
    description: "Schedule a 20-minute Zoom sync with a Cambridge curriculum specialist to review your child's goals.",
    iconName: "Video",
    actionText: "Book Advisor Sync",
    contactValue: "https://calendly.com/ebm-advising/sync",
  },
  {
    id: "consult-2",
    title: "Instant Advisor Callback",
    description: "Prefer a phone conversation? Provide your mobile number and we will connect in under 15 minutes.",
    iconName: "PhoneCall",
    actionText: "Request Voice Callback",
    contactValue: "tel:+923334541572",
  },
  {
    id: "consult-3",
    title: "Dedicated WhatsApp Line",
    description: "Message our advisory line immediately for questions about pricing plans, sibling options, or syllabi.",
    iconName: "MessageSquare",
    actionText: "Open WhatsApp Chat",
    contactValue: "https://wa.me/923334541572",
  },
];
