import { Injectable, NotFoundException } from "@nestjs/common";

@Injectable()
export class DashboardService {
  constructor(private prisma: any) {} // Replace with actual Prisma service in prod

  async getStudentDashboard(userId: string) {
    const profile = await this.prisma.studentProfile.findUnique({
      where: { userId },
      include: {
        statistics: true,
        streaks: true,
        subjectProgress: true,
        dailyLearning: {
          where: { date: new Date() }
        },
        achievements: {
          orderBy: { earnedAt: "desc" },
          take: 5
        },
        calendarEvents: {
          where: { eventDate: { gte: new Date() } },
          orderBy: { eventDate: "asc" },
          take: 5
        },
        dashboardNotifications: {
          where: { isRead: false },
          orderBy: { createdAt: "desc" },
          take: 10
        }
      }
    });

    if (!profile) {
      throw new NotFoundException("Student profile not found");
    }

    // Transform to expected StudentDashboardData interface
    return {
      studentName: profile.preferredName,
      currentGrade: "Grade 10", // Should be fetched from AcademicProfile
      currentLevel: "O-Level (Year 2)", 
      statistics: profile.statistics ? {
        overallCompletionPercentage: Number(profile.statistics.overallCompletionPercentage),
        currentAcademicYear: profile.statistics.currentAcademicYear,
        weeklyStudyHours: JSON.parse(profile.statistics.weeklyStudyHours),
        monthlyStudyHours: Number(profile.statistics.monthlyStudyHours),
        learningTrend: profile.statistics.learningTrend,
        masteryScore: profile.statistics.masteryScore,
        totalXp: profile.statistics.totalXp,
        learningStreakDays: profile.streaks?.currentStreak || 0
      } : {
        overallCompletionPercentage: 0,
        currentAcademicYear: "2026-2027",
        weeklyStudyHours: [0, 0, 0, 0, 0, 0, 0],
        monthlyStudyHours: 0,
        learningTrend: "FLAT",
        masteryScore: 0,
        totalXp: 0,
        learningStreakDays: 0
      },
      subjects: profile.subjectProgress.map((sp: any) => ({
        id: sp.id,
        name: sp.subjectName,
        code: sp.subjectCode,
        color: sp.colorCode,
        progressPercentage: Number(sp.progressPercentage),
        lessonsCompleted: sp.lessonsCompleted,
        totalLessons: sp.totalLessons,
        nextLessonTitle: sp.nextLessonTitle || "",
        pendingAssignments: sp.pendingAssignments,
        aiMasteryScore: sp.aiMasteryScore
      })),
      recentAssignments: [], // Usually fetched from Assignments module
      upcomingAssessments: [], // Usually fetched from Assessments module
      calendarEvents: profile.calendarEvents.map((ce: any) => ({
        id: ce.id,
        title: ce.title,
        date: ce.eventDate.toISOString().split("T")[0],
        time: ce.eventTime || "",
        type: ce.eventType,
        subjectName: ce.subjectId || "General" // Usually joined
      })),
      recentActivity: profile.dailyLearning.map((dl: any) => ({
        id: dl.id,
        type: dl.activityType,
        title: dl.title,
        description: "",
        timestamp: dl.createdAt.toISOString()
      })),
      achievements: profile.achievements.map((ach: any) => ({
        id: ach.id,
        title: ach.title,
        description: ach.description,
        iconUrl: ach.iconUrl || "sparkles",
        earnedAt: ach.earnedAt.toISOString(),
        xpAwarded: ach.xpAwarded
      })),
      aiRecommendations: [], // Usually generated by AI engine
      notifications: profile.dashboardNotifications.map((notif: any) => ({
        id: notif.id,
        title: notif.title,
        message: notif.message,
        type: notif.type,
        timestamp: notif.createdAt.toISOString(),
        read: notif.isRead
      }))
    };
  }

  // Fallback for missing features
  async mockDashboardData() {
    return {
      studentName: "Alex",
      currentGrade: "Grade 10",
      currentLevel: "O-Level (Year 2)",
      statistics: {
        overallCompletionPercentage: 68,
        currentAcademicYear: "2026-2027",
        weeklyStudyHours: [2, 3.5, 1, 4, 2.5, 5, 0],
        monthlyStudyHours: 42,
        learningTrend: "UP",
        masteryScore: 84,
        totalXp: 12450,
        learningStreakDays: 12,
      },
      subjects: [
        {
          id: "sub-eng",
          name: "English Language",
          code: "1123",
          color: "bg-blue-500",
          progressPercentage: 75,
          lessonsCompleted: 24,
          totalLessons: 32,
          nextLessonTitle: "Directed Writing: Reports",
          pendingAssignments: 1,
          aiMasteryScore: 88,
        },
        {
          id: "sub-math",
          name: "Mathematics",
          code: "4024",
          color: "bg-emerald-500",
          progressPercentage: 60,
          lessonsCompleted: 45,
          totalLessons: 75,
          nextLessonTitle: "Quadratic Equations",
          pendingAssignments: 2,
          aiMasteryScore: 72,
        }
      ],
      recentAssignments: [],
      upcomingAssessments: [],
      calendarEvents: [],
      recentActivity: [],
      achievements: [],
      aiRecommendations: [],
      notifications: []
    };
  }
}
